# Generated by Django 3.2.9 on 2021-12-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='phoneno',
            field=models.IntegerField(),
        ),
    ]
