# Generated by Django 3.2.9 on 2021-12-01 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_seller_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shops/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='shops/'),
        ),
    ]
