# Generated by Django 3.2.7 on 2021-12-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.CharField(default='arg', max_length=100),
            preserve_default=False,
        ),
    ]
